# Generated by Django 6.0.6 on 2026-06-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Galerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="photos/%Y/%m/")),
                ("nom_fichier", models.CharField(editable=False, max_length=255)),
                ("taille", models.PositiveIntegerField(help_text="octets", null=True)),
                ("largeur", models.PositiveIntegerField(help_text="pixels", null=True)),
                ("hauteur", models.PositiveIntegerField(help_text="pixels", null=True)),
                ("titre", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("date_prise_de_vue", models.DateTimeField(blank=True, null=True)),
                ("appareil", models.CharField(blank=True, max_length=100)),
                ("objectif", models.CharField(blank=True, max_length=100)),
                (
                    "ouverture",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("vitesse", models.CharField(blank=True, max_length=20)),
                ("iso", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
        ),
    ]
