# Generated by Django 6.0.6 on 2026-06-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0002_photo_auteur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="auteur",
        ),
        migrations.AddField(
            model_name="photo",
            name="auteur_email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="auteur_nom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="auteur_prenom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
