# Generated by Django 6.0.6 on 2026-06-16 16:53

import galeries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0004_alter_photo_iso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                storage=galeries.models.PhotoStorage(),
                upload_to=galeries.models.photo_upload_path,
            ),
        ),
    ]
