# Generated by Django 6.0.6 on 2026-06-16 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0005_alter_photo_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galerie",
            options={"verbose_name": "Galerie", "verbose_name_plural": "Galeries"},
        ),
        migrations.AddField(
            model_name="collection",
            name="galerie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="galeries.galerie",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="galerie",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="galerie",
            name="est_publique",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="galerie",
            name="nom",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="galerie",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="photos", to="galeries.collection"
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="galeries",
            field=models.ManyToManyField(
                blank=True, related_name="photos", to="galeries.galerie"
            ),
        ),
    ]
