# Generated by Django 6.0.6 on 2026-06-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0007_collection_nom"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together={("galerie", "slug")},
        ),
    ]
