# Generated by Django 6.0.6 on 2026-06-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0008_collection_slug_alter_collection_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AddField(
            model_name="photo",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="photos", to="galeries.tag"
            ),
        ),
    ]
