# Generated by Django 6.0.6 on 2026-06-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0009_tag_photo_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="nom",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="galerie",
            name="nom",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="photo",
            name="appareil",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="photo",
            name="objectif",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="tag",
            name="nom",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
