# Generated by Django 6.0.6 on 2026-06-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0010_alter_collection_nom_alter_galerie_nom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="masonry_layout_automatique",
            field=models.BooleanField(
                default=False,
                help_text="Ordre d'affichage défini par le photographe.",
                verbose_name="Masonry layout",
            ),
        ),
        migrations.AddField(
            model_name="galerie",
            name="masonry_layout_automatique",
            field=models.BooleanField(
                default=False,
                help_text="Ordre d'affichage défini par le photographe.",
                verbose_name="Masonry layout",
            ),
        ),
    ]
