# Generated by Django 6.0.6 on 2026-06-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeries", "0011_collection_masonry_layout_automatique_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="masonry_layout_automatique",
        ),
        migrations.RemoveField(
            model_name="galerie",
            name="masonry_layout_automatique",
        ),
        migrations.AddField(
            model_name="collection",
            name="masonry_layout_manuel",
            field=models.BooleanField(
                default=True,
                help_text="Ordre d'affichage défini par le photographe.",
                verbose_name="Masonry manuel",
            ),
        ),
        migrations.AddField(
            model_name="galerie",
            name="masonry_layout_manuel",
            field=models.BooleanField(
                default=True,
                help_text="Ordre d'affichage défini par le photographe.",
                verbose_name="Masonry manuel",
            ),
        ),
    ]
